### ISSUE TITLE
How to add the checker into LibreOffice in WIndows?

### ISSUE THREAD

**Issue by ooker777** [1ec5/hunspell-vi#15]
According to https://extensions.libreoffice.org/extensions/vietnamese-spellchecker-dictionary/1.0.110, there should be an OXT file in the ZIP to be imported with Extension Manager in LibreOffice Writer. But it's not. So how to add the checker?

**Comment by 1ec5** [comment]
Hi @ooker777, you can download the .oxt file directly from [the latest release’s page](https://github.com/1ec5/hunspell-vi/releases/latest/). The ZIP file contains the source code, not the final product.
