### ISSUE TITLE
Tiếng việt không dấu ?

### ISSUE THREAD

**Issue by chuongmep** [1ec5/hunspell-vi#18]
Dear Author , 
Wheather solution suppport vienamese no phonology
I have a isuse in this <a href="https://github.com/wooorm/dictionaries/pull/32">#32</a> 
Chào tác giả , 
Liệu có giải pháp nào cho tiếng việt không giấu không ? 
Tôi có một vấn đề cần kéo ở đây <a href="https://github.com/wooorm/dictionaries/pull/32">#32</a>

**Comment by 1ec5** [comment]
This project is a spell checker, but a spell checker for Vietnamese without diacritics would be extremely lax. Can you describe your use case? Depending on how you intend to use this functionality, it would be more efficient to use a standard regular expression tool to match against the following regular expression:

```regex
([BCDGHKLMNPQRSTVX]|[CKNP]H|G[HI]|NGH?|QU|T[HR])(A[IOUY]?|E[OU]?|I[AU]?|IEU?|O[AEO]?|OAY|U[AIOUY]|YA?)[MNPT]|[C]H?|N[GH]
```

For something stricter, [this JavaScript code](https://github.com/1ec5/avim/blob/18572ba2ded98cb5127b5f7ffda6b2b5e5ca3dca/components/transformer.js#L222-L340) from AVIM is very good at distinguishing valid from invalid Vietnamese words based on the base letters.

If you just need a tool to strip diacritics from Vietnamese text that has diacritics, then you can run [this Python script](https://github.com/1ec5/hunspell-vi/blob/507d07e36e9a56b9b29baccf974498a587d4aca3/tools/normalize.py) on the command line.

**Comment by chuongmep** [comment]
thanks for your infomation, I use to add some check spell from resharper plugin, code working perfect.
